/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DataFile } from "./DataFile";
import { DataFileCountArgs } from "./DataFileCountArgs";
import { DataFileFindManyArgs } from "./DataFileFindManyArgs";
import { DataFileFindUniqueArgs } from "./DataFileFindUniqueArgs";
import { CreateDataFileArgs } from "./CreateDataFileArgs";
import { UpdateDataFileArgs } from "./UpdateDataFileArgs";
import { DeleteDataFileArgs } from "./DeleteDataFileArgs";
import { DataFileService } from "../dataFile.service";
@graphql.Resolver(() => DataFile)
export class DataFileResolverBase {
  constructor(protected readonly service: DataFileService) {}

  async _dataFilesMeta(
    @graphql.Args() args: DataFileCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DataFile])
  async dataFiles(
    @graphql.Args() args: DataFileFindManyArgs
  ): Promise<DataFile[]> {
    return this.service.dataFiles(args);
  }

  @graphql.Query(() => DataFile, { nullable: true })
  async dataFile(
    @graphql.Args() args: DataFileFindUniqueArgs
  ): Promise<DataFile | null> {
    const result = await this.service.dataFile(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DataFile)
  async createDataFile(
    @graphql.Args() args: CreateDataFileArgs
  ): Promise<DataFile> {
    return await this.service.createDataFile({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => DataFile)
  async updateDataFile(
    @graphql.Args() args: UpdateDataFileArgs
  ): Promise<DataFile | null> {
    try {
      return await this.service.updateDataFile({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DataFile)
  async deleteDataFile(
    @graphql.Args() args: DeleteDataFileArgs
  ): Promise<DataFile | null> {
    try {
      return await this.service.deleteDataFile(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
